{% set version = "2.10.3" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}



package:
  name: coincbc
  version: {{ version }}

source:
  fn: Cbc-{{ version }}.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
  sha256: ad388357129497c1cc3be50c3707b1995fddf0a4188abc8e3669173f0179ecff

build:
  number: 0
  skip: true  # [win]
  features:

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if 'toolchain' in compiler('c') %}
    - {{ compiler('fortran') }}  # [osx]
    {% else %}
    - {{ compiler('fortran') }}  # [unix]
    {% endif %}
  host:
    - libblas
    - libcblas
    - liblapack
  run:

test:
  commands:
    - test -f "${PREFIX}/lib/libCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libCbcSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCgl{{ libext }}"
    - test -f "${PREFIX}/lib/libClp{{ libext }}"
    - test -f "${PREFIX}/lib/libClpSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCoinUtils{{ libext }}"
    - test -f "${PREFIX}/lib/libOsi{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiClp{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCommonTests{{ libext }}"

about:
  home: http://www.coin-or.org/
  license: Eclipse v1.0
  summary: "Cbc (Coin-or branch and cut) is an open-source mixed integer programming solver written in C++."

extra:
  recipe-maintainers:
    - scopatz
    - gidden
    - whart222
    - jjhelmus
