{% set version = "2.10.1" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}

{% set variant = "openblas" %}


package:
  name: coincbc
  version: {{ version }}

source:
  fn: Cbc-{{ version }}.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
  sha256: ccf12d67d5dbf40bf7363c30955938709f293f087d87cb78cac9d3db9f5bcf2b

build:
  number: 0
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if 'toolchain' in compiler('c') %}
    - {{ compiler('fortran') }}  # [osx]
    {% else %}
    - {{ compiler('fortran') }}  # [unix]
    {% endif %}
  host:
    - blas 1.1 {{ variant }}
    - openblas
  run:
    - blas 1.1 {{ variant }}
    - openblas

test:
  commands:
    - test -f "${PREFIX}/lib/libCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libCbcSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCgl{{ libext }}"
    - test -f "${PREFIX}/lib/libClp{{ libext }}"
    - test -f "${PREFIX}/lib/libClpSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCoinUtils{{ libext }}"
    - test -f "${PREFIX}/lib/libOsi{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiClp{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCommonTests{{ libext }}"

about:
  home: http://www.coin-or.org/
  license: Eclipse v1.0
  summary: "Cbc (Coin-or branch and cut) is an open-source mixed integer programming solver written in C++."

extra:
  recipe-maintainers:
    - scopatz
    - gidden
    - whart222
    - jjhelmus
