# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ljfLNgWpgx8WQQCGIpBWNnx8bcnyOF3sOwr6IxkxbDaRvRG37kyV901iaYnceKqNIK0MhIQnIUsM3ViIhgkE7m8KVPYqGNbgO1GQWzRq9d6aeFuEPdi8g9/K+9mb3L43qEzEvYkn1aQnd6aTc9GAGYkUIeetBmDc4f5I2JPWbNItSC1e9xPORebDKcs2PCRi2LF+phXeS8tXnYFJlggCVqsuBlegPaBwG8EGUUOILivh2hrisikSRSHSikOX0ShVocv0PWRgeYdh8u308tC5cf+0P95inPHkfJ1TlByNtEFn4jFdSepjwRgkKtAKcRBiUwupJoGeN4GfmWWGTKpGUk1Lj7ccU8gyUwSnJWdSampWUMvYZJaEWE+vN4dDBtl+bGaBRk2x7rof6QkBURVscJ/NhLHCTXlsXqUNhO4xcEpgVeiePJEs6dezwu6RVEAhW4joihS8axjFtGXfCD991OLUhc29XZxwtvqgF/j2jul2jnyMRbAHZdeX3WHUTB85xmO/HQ1rJslGSHfzO4jbm0kqwAr8dIVPkHnKeeVtqR8qdcNS4+inisLOhCenj0KmFk0ub3gg6v3+7p3vSNeu0blg48lynBCIIsRLolrQvq+oF8yHk5fYE6C0ciSXyToV/A/n/UPHcdgOPkW8IG0n21WhVDscKqPxWBh8g+3BLeQ="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
