travis:
  secure:
    BINSTAR_TOKEN: ljfLNgWpgx8WQQCGIpBWNnx8bcnyOF3sOwr6IxkxbDaRvRG37kyV901iaYnceKqNIK0MhIQnIUsM3ViIhgkE7m8KVPYqGNbgO1GQWzRq9d6aeFuEPdi8g9/K+9mb3L43qEzEvYkn1aQnd6aTc9GAGYkUIeetBmDc4f5I2JPWbNItSC1e9xPORebDKcs2PCRi2LF+phXeS8tXnYFJlggCVqsuBlegPaBwG8EGUUOILivh2hrisikSRSHSikOX0ShVocv0PWRgeYdh8u308tC5cf+0P95inPHkfJ1TlByNtEFn4jFdSepjwRgkKtAKcRBiUwupJoGeN4GfmWWGTKpGUk1Lj7ccU8gyUwSnJWdSampWUMvYZJaEWE+vN4dDBtl+bGaBRk2x7rof6QkBURVscJ/NhLHCTXlsXqUNhO4xcEpgVeiePJEs6dezwu6RVEAhW4joihS8axjFtGXfCD991OLUhc29XZxwtvqgF/j2jul2jnyMRbAHZdeX3WHUTB85xmO/HQ1rJslGSHfzO4jbm0kqwAr8dIVPkHnKeeVtqR8qdcNS4+inisLOhCenj0KmFk0ub3gg6v3+7p3vSNeu0blg48lynBCIIsRLolrQvq+oF8yHk5fYE6C0ciSXyToV/A/n/UPHcdgOPkW8IG0n21WhVDscKqPxWBh8g+3BLeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
