travis:
  secure:
    BINSTAR_TOKEN: YowlTf1QrjqSR87xaRF7kR93B/ByNvIwgwr94TBdh3q/j07IghF2s37sj+4xLHSlTrj1P4YZDZ226HZUpn5h1jv9qcdinSmXtk/b2/SdMgJS1+kPHR2WclZ4/KAQmnvWovxy+JXu3dezFsda639mSD90MdbK6xHN45SewXF0JLi9ySTgfiJO0R6ZMFZ6ilXnez1+4M2S3/mMr/IUGn+J9SSfesBVYFDDQlHy69XKEZVcMlEQ3mDVBbW/wsG2SWDs6IP9oTzZwsqBxTUc6G/x7T8JsHvs5TwJY7KrW0mrFtpdEQdfh4FgZE9XfstYojbiBB0D/14nlmXHDt34dIjcW+13TSIetj+HrNVu3uNU6N7zRVuTAVU8jMN0D+Tw2F4U5zgVsN00gsP+39mZqSg1mpE3s7xRJz8Pdoe1jzGFdL75T+xFJQ2CA0phkPhl990khXE5UPZHKgSkhrVTQoFSt3iOsFyb6Ecw0+tXMIXY2qMQnZa0ebQQPF8JKj6VkKBCKnH02f5yxw5AO4uTvcPKleUF6qRCBTUmRTbRqIleoON2Q0RvE0e9KlwZkvZoB2p8PyQ1TmNVSN0q1LGmWrCi3Aw4UBs2cIsfKG2AVvZg93PthrK42QdPyFr58xQYpj2OHNLRkK7et9nyv5xQ9D07ZYL41QrNldVHQ304hxhv/T0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
